### PR TITLE
added a BSD 3-clause license

### PR DESCRIPTION
**Pull request by gidden**
took a stab at a reasonable license clause. again I'd prefer for everyone to give a +1 before pulling if possible.

### CODE REVIEW

**Comment by coroa** [comment]
Why the loose BSD? GPL is too complicated or restrictive? Am fine with both!

**Comment by sjpfenninger** [comment]
We can't use GPL-licensed code inside non-GPL licensed projects, so I prefer a permissive license

**Comment by gidden** [comment]
exactly

**Comment by ojdo** [comment]
+1; no one's forced to contribute their most valuable GPL'ed functions/models here.

**Comment by gidden** [comment]
ok, then this should be good to go. who wants to pull? =)

**Pull request merged**
